### ISSUE TITLE
整挺好，不过用了一会窝ip就被403了

### ISSUE THREAD

**Issue by FanYang221** [roadwide/WeiBoRelation#1]

**Comment by roadwide** [comment]
确实会这样，一定时间内请求频率到上限了，我记得我写出错等待这个功能了。想写通过ip池代理的功能，可是现在没什么空。以后有机会吧

**Comment by FanYang221** [comment]
刚才发现是窝开的全局代理，代理的ip被封了，关了后还是可以的，这东西也不是说封了就一直请求不了，就是中间有几个会出现出错等待的问题，并且时间还挺长的delay的时间一般都到30s，我直接把返回不是200的跳过了
